export const symptoms = [
  "itching",
  "skin_rash",
  "nodal_skin_eruptions",
  "continuous_sneezing",
  "shivering",
  "chills",
  "joint_pain",
  "stomach_pain",
  "acidity",
  "ulcers_on_tongue",
  "muscle_wasting",
  "vomiting",
  "burning_micturition",
  "spotting_urination",
  "fatigue",
  "weight_gain",
  "anxiety",
  "cold_hands_and_feets",
  "mood_swings",
  "weight_loss",
  "restlessness",
  "lethargy",
  "patches_in_throat",
  "irregular_sugar_level",
  "cough",
  "high_fever",
  "sunken_eyes",
  "breathlessness",
  "sweating",
  "dehydration",
  "indigestion",
  "headache",
  "yellowish_skin",
  "dark_urine",
  "nausea",
  "loss_of_appetite",
  "pain_behind_the_eyes",
  "back_pain",
  "constipation",
  "abdominal_pain",
  "diarrhoea",
  "mild_fever",
  "yellow_urine",
  "yellowing_of_eyes",
  "acute_liver_failure",
  "fluid_overload",
  "swelling_of_stomach",
  "swelled_lymph_nodes",
  "malaise",
  "blurred_and_distorted_vision",
  "phlegm",
  "throat_irritation",
  "redness_of_eyes",
  "sinus_pressure",
  "runny_nose",
  "congestion",
  "chest_pain",
  "weakness_in_limbs",
  "fast_heart_rate",
  "pain_during_bowel_movements",
  "pain_in_anal_region",
  "bloody_stool",
  "irritation_in_anus",
  "neck_pain",
  "dizziness",
  "cramps",
  "bruising",
  "obesity",
  "swollen_legs",
  "swollen_blood_vessels",
  "puffy_face_and_eyes",
  "enlarged_thyroid",
  "brittle_nails",
  "swollen_extremeties",
  "excessive_hunger",
  "extra_marital_contacts",
  "drying_and_tingling_lips",
  "slurred_speech",
  "knee_pain",
  "hip_joint_pain",
  "muscle_weakness",
  "stiff_neck",
  "swelling_joints",
  "movement_stiffness",
  "spinning_movements",
  "loss_of_balance",
  "unsteadiness",
  "weakness_of_one_body_side",
  "loss_of_smell",
  "bladder_discomfort",
  "foul_smell_of_urine",
  "continuous_feel_of_urine",
  "passage_of_gases",
  "internal_itching",
  "toxic_look_(typhos)",
  "depression",
  "irritability",
  "muscle_pain",
  "altered_sensorium",
  "red_spots_over_body",
  "belly_pain",
  "abnormal_menstruation",
  "dischromic_patches",
  "watering_from_eyes",
  "increased_appetite",
  "polyuria",
  "family_history",
  "mucoid_sputum",
  "rusty_sputum",
  "lack_of_concentration",
  "visual_disturbances",
  "receiving_blood_transfusion",
  "receiving_unsterile_injections",
  "coma",
  "stomach_bleeding",
  "distention_of_abdomen",
  "history_of_alcohol_consumption",
  "blood_in_sputum",
  "prominent_veins_on_calf",
  "palpitations",
  "painful_walking",
  "pus_filled_pimples",
  "blackheads",
  "scurring",
  "skin_peeling",
  "silver_like_dusting",
  "small_dents_in_nails",
  "inflammatory_nails",
  "blister",
  "red_sore_around_nose",
  "yellow_crust_ooze",
];

export const categorizedSymtoms = {
  "Respiratory Symptoms": {
    "Continuous Sneezing": "continuous_sneezing",
    Shivering: "shivering",
    Chills: "chills",
    Cough: "cough",
    Breathlessness: "breathlessness",
    Phlegm: "phlegm",
    "Throat Irritation": "throat_irritation",
    "Redness of Eyes": "redness_of_eyes",
    "Sinus Pressure": "sinus_pressure",
    "Runny Nose": "runny_nose",
    Congestion: "congestion",
    "Rusty Sputum": "rusty_sputum",
    "Blood in Sputum": "blood_in_sputum",
  },
  "Skin and Rashes": {
    Itching: "itching",
    "Skin Rash": "skin_rash",
    "Nodal Skin Eruptions": "nodal_skin_eruptions",
    "Ulcers on Tongue": "ulcers_on_tongue",
    "Patches in Throat": "patches_in_throat",
    "Yellowish Skin": "yellowish_skin",
    "Dark Urine": "dark_urine",
    "Red Spots Over Body": "red_spots_over_body",
    "Dischromic Patches": "dischromic_patches",
    Blister: "blister",
    "Red Sore Around the Nose": "red_sore_around_nose",
    "Yellow Crust Ooze": "yellow_crust_ooze",
    Bruising: "bruising",
    "Drying and Tingling Lips": "drying_and_tingling_lips",
    Blackheads: "blackheads",
    "Skin Peeling": "skin_peeling",
  },
  "Joint and Muscle Symptoms": {
    "Joint Pain": "joint_pain",
    "Muscle Wasting": "muscle_wasting",
    "Muscle Weakness": "muscle_weakness",
    "Swelling Joints": "swelling_joints",
    "Stiff Neck": "stiff_neck",
    "Spinning Movements": "spinning_movements",
    "Loss of Balance": "loss_of_balance",
    Unsteadiness: "unsteadiness",
    "Weakness of One Body Side": "weakness_of_one_body_side",
    "Knee Pain": "knee_pain",
    "Hip Joint Pain": "hip_joint_pain",
    "Movement Stiffness": "movement_stiffness",
    "Back Pain": "back_pain",
    "Neck Pain": "neck_pain",
    "Muscle Pain": "muscle_pain",
    "Belly Pain": "belly_pain",
  },
  "Gastrointestinal Symptoms": {
    "Stomach Pain": "stomach_pain",
    Acidity: "acidity",
    Vomiting: "vomiting",
    "Spotting Urination": "spotting_urination",
    Indigestion: "indigestion",
    Constipation: "constipation",
    "Abdominal Pain": "abdominal_pain",
    Diarrhoea: "diarrhoea",
    "Pain During Bowel Movements": "pain_during_bowel_movements",
    "Pain in Anal Region": "pain_in_anal_region",
    "Bloody Stool": "bloody_stool",
    "Irritation in Anus": "irritation_in_anus",
    "Passage of Gases": "passage_of_gases",
    "Internal Itching": "internal_itching",
    "Stomach Bleeding": "stomach_bleeding",
    "Distention of Abdomen": "distention_of_abdomen",
    "Swelling of Stomach": "swelling_of_stomach",
    Nausea: "nausea",
  },
  "Fever and Infection-Related Symptoms": {
    "High Fever": "high_fever",
    Sweating: "sweating",
    Dehydration: "dehydration",
    "Sunken Eyes": "sunken_eyes",
    "Mild Fever": "mild_fever",
    "Loss of Appetite": "loss_of_appetite",
    "Swelled Lymph Nodes": "swelled_lymph_node",
    Coma: "coma",
    Malaise: "malaise",
  },
  "Neurological Symptoms": {
    Headache: "headache",
    Dizziness: "dizziness",
    Cramps: "cramps",
    "Altered Sensorium": "altered_sensorium",
    "Visual Disturbances": "visual_disturbances",
    "Lack of Concentration": "lack_of_concentration",
    "Slurred Speech": "slurred_speech",
    "Pain Behind the Eyes": "pain_behind_the_eyes",
    "Blurred and Distorted Vision": "blurred_and_distorted_vision",
    "Weakness in Limbs": "weakness_in_limbs",
    "Loss of Smell": "loss_of_smell",
  },
  "Urinary Symptoms": {
    "Burning Micturition": "burning_micturition",
    "Yellow Urine": "yellow_urine",
    "Continuous Feeling of Urine": "continuous_feel_of_urine",
    "Foul Smell of Urine": "foul_smell_of_urine",
    "Bladder Discomfort": "bladder_discomfort",
  },
  "Mental and Emotional Symptoms": {
    Anxiety: "anxiety",
    "Mood Swings": "mood_swings",
    Depression: "depression",
    Irritability: "irritability",
    Restlessness: "restlessness",
  },
  "Endocrine and Metabolic Symptoms": {
    "Weight Gain": "weight_gain",
    "Weight Loss": "weight_loss",
    Lethargy: "lethargy",
    "Cold Hands and Feet": "cold_hands_and_feets",
    Fatigue: "fatigue",
    "Increased Appetite": "increased_appetite",
    Polyuria: "polyuria",
    "Excessive hunger": "excessive_hunger",
    Obesity: "obesity",
    "Irregular Sugar Level": "irregular_sugar_level",
  },
  "Cardiovascular Symptoms": {
    "Chest Pain": "chest_pain",
    "Fast Heart Rate": "fast_heart_rate",
    "Fluid Overload": "fluid_overload",
    Palpitations: "palpitations",
  },
  "Hepatic (Liver) Symptoms": {
    "Yellowing of Eyes": "yellowing_of_eyes",
    "Acute Liver Failure": "acute_liver_failure",
  },
  "Other Miscellaneous Symptoms": {
    "Swollen Legs": "swollen_legs",
    "Swollen Blood Vessels": "swollen_blood_vessels",
    "Puffy Face and Eyes": "puffy_face_and_eyes",
    "Enlarged Thyroid": "enlarged_thyroid",
    "Brittle Nails": "brittle_nails",
    "Swollen Extremities": "swollen_extremeties",
    "Family History": "family_history",
    "Mucoid Sputum": "mucoid_sputum",
    "Receiving Blood Transfusion": "receiving_blood_transfusion",
    "Receiving Unsterile Injections": "receiving_unsterile_injections",
    "Extra Marital Contacts": "extra_marital_contacts",
    "Toxic Look (Typhos)": "toxic_look_(typhos)",
    "Abnormal Menstruation": "abnormal_menstruation",
    "Watering from Eyes": "watering_from_eyes",
    "History of Alcohol Consumption": "history_of_alcohol_consumption",
    "Prominent Veins on Calf": "prominent_veins_on_calf",
    "Painful Walking": "painful_walking",
    "Pus Filled Pimples": "pus_filled_pimples",
    Scurring: "scurring",
    "Silver Like Dusting": "silver_like_dusting",
    "Small Dents in Nails": "small_dents_in_nails",
    "Inflammatory Nails": "inflammatory_nails",
  },
};
